databases:
  - name: Budget-App
    databaseName: budget_app_dhzt
    user: budget_app_dhzt_user

services:
  - type: web
    name: Budget-App
    runtime: ruby
    buildCommand: "./bin/render-build.bat"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Budget-App
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false